name: CI/CD For cloud decode

on:
  push:
    branches:
      -main

jobs:
  -build-and-deploy:
    runs-on: ubuntu-latest
  steps:
    -name: checkout repository
    uses: actions/checkout@v3

    -name: Configure AWS Credentials
    uses: aws-actions/v1-node16
    with: 
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    
    -name: Deploy website to s3
    run: aws s3 sync .s3://         --delete
    